-- MySQL Script generated by MySQL Workbench
-- Wed Feb 24 11:38:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moca` DEFAULT CHARACTER SET utf8 ;
USE `moca` ;

-- -----------------------------------------------------
-- Table `moca`.`userInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`userInfo` (
  `userEmail` VARCHAR(30) NOT NULL,
  `userPw` VARCHAR(20) NOT NULL,
  `userNickname` VARCHAR(10) NULL DEFAULT NULL,
  `userName` VARCHAR(10) NOT NULL,
  `userPhone` VARCHAR(15) NOT NULL,
  `userBirth` DATE NULL DEFAULT NULL,
  `userImg` VARCHAR(50) NULL DEFAULT NULL,
  `userInsertDate` DATETIME NULL DEFAULT NULL,
  `userDeleteDate` DATETIME NULL DEFAULT NULL,
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC) VISIBLE,
  UNIQUE INDEX `userNickname_UNIQUE` (`userNickname` ASC) VISIBLE,
  PRIMARY KEY (`userEmail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`menu` (
  `menuNo` INT NOT NULL AUTO_INCREMENT,
  `menuName` VARCHAR(45) NULL DEFAULT NULL,
  `menuPrice` INT NULL DEFAULT NULL,
  `menuImg` VARCHAR(45) NULL DEFAULT NULL,
  `menuCalorie` VARCHAR(10) NULL DEFAULT NULL,
  `menuInformation` VARCHAR(100) NULL DEFAULT NULL,
  `menuCategory` VARCHAR(10) NULL,
  PRIMARY KEY (`menuNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`review` (
  `userInfo_userEmail` VARCHAR(30) NOT NULL,
  `menu_menuNo` INT NOT NULL,
  `reviewContent` TEXT NULL DEFAULT NULL,
  `reviewStar` DOUBLE NULL DEFAULT NULL,
  `reviewImg` VARCHAR(50) NULL DEFAULT NULL,
  `reviewInsertDate` DATETIME NULL DEFAULT NULL,
  INDEX `fk_review_userInfo_idx` (`userInfo_userEmail` ASC) VISIBLE,
  INDEX `fk_review_menu1_idx` (`menu_menuNo` ASC) VISIBLE,
  CONSTRAINT `fk_review_userInfo`
    FOREIGN KEY (`userInfo_userEmail`)
    REFERENCES `moca`.`userInfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_menu1`
    FOREIGN KEY (`menu_menuNo`)
    REFERENCES `moca`.`menu` (`menuNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`brand` (
  `brandNo` INT NOT NULL AUTO_INCREMENT,
  `brandName` VARCHAR(45) NULL DEFAULT NULL,
  `brandImg` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`brandNo`),
  UNIQUE INDEX `brandNo_UNIQUE` (`brandNo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`have`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`have` (
  `brand_brandNo` INT NOT NULL,
  `menu_menuNo` INT NOT NULL,
  INDEX `fk_have_brand1_idx` (`brand_brandNo` ASC) VISIBLE,
  INDEX `fk_have_menu1_idx` (`menu_menuNo` ASC) VISIBLE,
  CONSTRAINT `fk_have_brand1`
    FOREIGN KEY (`brand_brandNo`)
    REFERENCES `moca`.`brand` (`brandNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_have_menu1`
    FOREIGN KEY (`menu_menuNo`)
    REFERENCES `moca`.`menu` (`menuNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`like` (
  `userInfo_userEmail` VARCHAR(30) NOT NULL,
  `menu_menuNo` INT NOT NULL,
  INDEX `fk_like_userInfo1_idx` (`userInfo_userEmail` ASC) VISIBLE,
  INDEX `fk_like_menu1_idx` (`menu_menuNo` ASC) VISIBLE,
  CONSTRAINT `fk_like_userInfo1`
    FOREIGN KEY (`userInfo_userEmail`)
    REFERENCES `moca`.`userInfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_menu1`
    FOREIGN KEY (`menu_menuNo`)
    REFERENCES `moca`.`menu` (`menuNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`board` (
  `boardNo` INT NOT NULL AUTO_INCREMENT,
  `boardTitle` VARCHAR(30) NULL DEFAULT NULL,
  `boardContent` TEXT NULL DEFAULT NULL,
  `boardImg` VARCHAR(45) NULL DEFAULT NULL,
  `boardInsertDate` DATETIME NULL DEFAULT NULL,
  `boardDeleteDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`boardNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`write`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`write` (
  `userInfo_userEmail` VARCHAR(30) NOT NULL,
  `board_boardNo` INT NOT NULL,
  INDEX `fk_write_userInfo1_idx` (`userInfo_userEmail` ASC) VISIBLE,
  INDEX `fk_write_board1_idx` (`board_boardNo` ASC) VISIBLE,
  CONSTRAINT `fk_write_userInfo1`
    FOREIGN KEY (`userInfo_userEmail`)
    REFERENCES `moca`.`userInfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_write_board1`
    FOREIGN KEY (`board_boardNo`)
    REFERENCES `moca`.`board` (`boardNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`tip` (
  `tipNo` INT NOT NULL AUTO_INCREMENT,
  `tipImg` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`tipNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`comment` (
  `commentNo` INT NOT NULL AUTO_INCREMENT,
  `board_boardNo` INT NOT NULL,
  `commentNo` VARCHAR(30) NOT NULL,
  `commentContent` VARCHAR(100) NULL DEFAULT NULL,
  `commentInsertDate` DATETIME NULL DEFAULT NULL,
  INDEX `fk_comment_board1_idx` (`board_boardNo` ASC) VISIBLE,
  INDEX `fk_comment_userInfo1_idx` (`commentNo` ASC) VISIBLE,
  PRIMARY KEY (`commentNo`),
  CONSTRAINT `fk_comment_board1`
    FOREIGN KEY (`board_boardNo`)
    REFERENCES `moca`.`board` (`boardNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_userInfo1`
    FOREIGN KEY (`commentNo`)
    REFERENCES `moca`.`userInfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moca`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moca`.`reply` (
  `comment_commentNo` INT NOT NULL,
  `userInfo_userEmail` VARCHAR(30) NOT NULL,
  `replyContent` VARCHAR(45) NULL DEFAULT NULL,
  `replyInsertDate` DATETIME NULL DEFAULT NULL,
  INDEX `fk_reply_comment1_idx` (`comment_commentNo` ASC) VISIBLE,
  INDEX `fk_reply_userInfo1_idx` (`userInfo_userEmail` ASC) VISIBLE,
  CONSTRAINT `fk_reply_comment1`
    FOREIGN KEY (`comment_commentNo`)
    REFERENCES `moca`.`comment` (`commentNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reply_userInfo1`
    FOREIGN KEY (`userInfo_userEmail`)
    REFERENCES `moca`.`userInfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
