# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moca' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moca
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'  # 사용자 관리


  pod 'Firebase/Core' # 구글 로그인 
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  pod 'IBPCollectionViewCompositionalLayout'

  pod 'Kanna','~>5.0.0' 

  pod 'naveridlogin-sdk-ios' # 네이버 로그인 
  pod 'Alamofire', '~> 5.1'

  pod 'Cosmos' # 
  pod 'TinyConstraints'

end
